version: "3"

volumes:
        produtosdata:

networks:
        frontend:
        backend:

services:

        mysql:
          image: "mysql:5.7"
          volumes:
            - produtosdata:/var/lib/mysql
          networks:
            - backend
          environment:
            - MYSQL_ROOT_PASSWORD=159753
            - bind-address=0.0.0.0
          ports:
            - 3306:3306
          expose:
            - 3306
        mvc:
          build:
           context: .
           dockerfile: Dockerfile
          networks:
              - backend
              - frontend
          ports:
              - 5000:80
          environment:
              - DBHOST=mysql
          depends_on:
              - mysql
          